#
# This exist just for quick cleaning of the subdirectories.
# For the real configuration, see Makefile.common` and `common-conf.h`.
#

all:
	@echo "Recursive make not supported"

clean:
	$(MAKE) -C gw clean
	$(MAKE) -C wearable clean

distclean:
	$(MAKE) -C gw distclean
	$(MAKE) -C wearable distclean
